language: python
python:
  - "2.7"
  - "3.4"
before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y libgdal1h gdal-bin libgdal-dev
install:
  - pip install numpy>=1.8 Cython
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - pip install -e .
script: "coverage run --include *rasterstats* setup.py test"
after_success:
  - coveralls
