# This is the config file for building GDAL and running its autotest suite
# with Travis-ci.org

language: python
before_install:
  - "sudo apt-get update -qq -y "
  - "sudo apt-get install -qq -y python-pandas libgdal-dev gdal-bin python-gdal python-pip python-numpy build-essential git python-dev"
virtualenv:
  system_site_packages: true
python:
  - "2.7"
install:
  - "pip install shapely coveralls --use-mirrors"
  - "pip install git+https://github.com/geopandas/geopandas.git"
script: "coverage run --include *rasterstats* setup.py test"
after_success:
  - coveralls