# This is the config file for building GDAL and running its autotest suite
# with Travis-ci.org

language: python
before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq libgdal-dev gdal-bin python-gdal python-pip python-numpy libspatialindex-dev libspatialindex1 build-essential git atop python-dev python-dateutil"
python:
  - "2.6"
  - "2.7"
install:
  - "pip install shapely"
script: "python setup.py test"