language: python
sudo: false
cache:
  directories:
    - ~/.cache/pip
env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      env: NEWNUMPY=true

before_install:
  - pip install -U pip setuptools --upgrade
  - pip install wheel
install:
  - if [[ "$NEWNUMPY" = true ]]; then pip install numpy>=1.16; fi
  - pip install numpy "rasterio>=1.0a12"
  - pip install -r requirements_dev.txt
  - pip install coveralls
  - pip install -e .
script: py.test --cov rasterstats --cov-report term-missing
after_success:
  - coveralls
